services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - "./backend:/usr/src/source"
    user: "root"
    ports:
      - "${APP_PORT:-4000}:3000"
    environment:
      - ENVIRONMENT=development
      - MONGO_URL=mongodb://${DB_USERNAME:-deploynest}:${DB_PASSWORD:-password}@mongo:27017/DeployNest?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-deploynest}
    command: "npm run watch"

  mongo:
    image: mongo
    restart: always
    ports:
      - 4001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-deploynest}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-password}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME:-deploynest}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME:-deploynest}:${DB_PASSWORD:-password}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 4003:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-deploynest}